name: "Setup Node.js Environment"
description: "Setup Node.js with caching and dependency installation"
inputs:
  node-version:
    description: "Node.js version to install"
    required: false
    default: "24"
  install-deps:
    description: "Whether to install dependencies"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Setup safe-chain
      if: runner.os != 'Windows'
      shell: bash
      run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      run: npm ci
      shell: bash
